### PR TITLE
[Integration Test] verify if os support gVisor in the cloudprofile

### PR DESCRIPTION
**Pull request by vpnachev**
**What this PR does / why we need it**:
Verify if os support gVisor in the cloudprofile of the shoot cluster.

Whether a OS supprots gVisor or not is specified in the cloudprofile resource and this extension should be OS agnostic.
I have successfully run the tests with both gardenlinux and flatcar.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Opened as draft till #18 is merged.

**Release note**:

```improvement operator

```

### CODE REVIEW

**Comment by vpnachev** [comment]
I will re-work this PR to run the validation against the cloud profile of the shoot.

**Review by dguendisch — COMMENTED** [review]
/lgtm

**Review by rfranzke — APPROVED** [review]
/lgtm

**Pull request merged**
