### PR TITLE
Fix passing down IgnoreOperationAnnotation to AddArgs

### PR DESCRIPTION
**Pull request by ppalucki**
**What this PR does / why we need it**:

When running locally using Makefile - value [IGNORE_OPERATION_ANNOTATION := true](https://github.com/gardener/gardener-extension-runtime-gvisor/blob/master/Makefile#L25) is not passed to `containerRuntime.AddArgs` and therefore improper watch is set here
https://github.com/gardener/gardener-extension-runtime-gvisor/blob/master/vendor/github.com/gardener/gardener/extensions/pkg/controller/containerruntime/controller.go#L91

The end result is, the "watch" is set on `ContainerRuntime` instead of `Cluster` and its "containerRuntimeList" as the code suggests so the whole "ignoreRuntimeOperation" feature **may** not function properly. 

I cannot confirm that because I don't know what was the purpose from the beginning.

**Which issue(s) this PR fixes**:
Fixes # - not issued - not sure is it bug or not?

**Special notes for your reviewer**:

I don't yet know is this really bug and how important this flag is because I found this *inconsistency* when I tried to understand what is the purpose of this flag - so do not know how to affects others - maybe it works as expected anyway.

**Release note**:

```improvement operator
NONE
```

I'm attaching screenshot from my debugging session:

image

without this fix it never go inside this conditional.

### CODE REVIEW

**Comment by gardener-robot-ci-2** [comment]
Thank you @ppalucki for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by rfranzke — APPROVED** [review]
/lgtm
/reviewed ok-to-test

@ppalucki Please sign the CLA

**Comment by rfranzke** [comment]
@ppalucki Can you run `make generate` to fix the failing CI?

**Comment by rfranzke** [comment]
ping @ppalucki

**Comment by ppalucki** [comment]
@rfranzke done - I had some stupid issue because I couldn't force "make generate" to work - surprisingly my sources weren't in GOPATH and wasn't expecting that is still required after introducing go.mod and I was getting strange "paths are broken" and similar - should be fine right know.

**Review by rfranzke — APPROVED** [review]

**Pull request merged**
